name: Selenium Tests CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      # Step 3: Set up Chrome Browser (already installed on Windows runners)

      - name: Check Chrome version
        run: chrome --version

      # Step 4: Set up ChromeDriver (matches Chrome version automatically)
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          version: latest

      # Step 5: Cache Maven dependencies
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 6: Run Selenium Tests
      - name: Run Maven Selenium Tests
        run: mvn clean install

      # Step 7: Upload Extent Report
      - name: Upload Extent HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Selenium-ExtentReport
          path: |
            reports/
            test-output/
